name: KICS Security Scan

on:
  workflow_call: {}

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  kics:
    name: KICS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create results directory
        run: mkdir -p kics-results

      - name: KICS scan
        uses: Checkmarx/kics-action@v1.7.0
        with:
          path: "./terraform"
          output_path: "kics-results"
          output_formats: "json,sarif"
          fail_on: high
          enable_comments: true
          platform_type: terraform
          output_name: "scan-results"

      - name: Display KICS results
        if: always()
        run: |
          echo "KICS Scan Results:"
          ls -la kics-results/
          if [ -f "kics-results/scan-results.sarif" ]; then
            echo "SARIF file exists"
          else
            echo "SARIF file not found"
          fi

      - name: Upload KICS Results - JSON
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kics-results-json
          path: kics-results/scan-results.json
          retention-days: 7

      - name: Upload KICS Results - SARIF
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kics-results-sarif
          path: kics-results/scan-results.sarif
          retention-days: 7

      - name: Upload KICS Results to Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: kics-results/scan-results.sarif
          category: KICS
