name: KICS Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  kics:
    name: KICS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: KICS scan
        uses: Checkmarx/kics-action@v1.7.0
        with:
          path: "./vpc"
          output_path: "./kics-results"
          output_formats: "json"
          fail_on: high
          exclude_paths: .kicsignore
          enable_comments: true
          platform_type: terraform
          output_name: kics-results.json

      - name: Upload KICS Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: kics-results
          path: kics-results/
          retention-days: 7
