name: KICS Scan

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight

jobs:
  kics:
    name: KICS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create results directory
        run: mkdir -p kics-results

      - name: KICS scan
        uses: Checkmarx/kics-action@v1.7.0
        with:
          path: "./vpc"
          output_path: "kics-results"
          output_formats: "json,sarif"
          fail_on: high
          exclude_paths: .kicsignore
          enable_comments: true
          platform_type: terraform
          output_name: kics-results

      - name: List results directory
        if: always()
        run: |
          echo "Contents of kics-results directory:"
          ls -la kics-results/

      - name: Upload KICS Results - JSON
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kics-results-json
          path: kics-results/*.json
          retention-days: 7

      - name: Upload KICS Results - SARIF
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kics-results-sarif
          path: kics-results/*.sarif
          retention-days: 7

      - name: Upload KICS Results to Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: kics-results/results.sarif
