name: KICS Security Scan

on:
  workflow_call: {}

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  kics:
    name: KICS Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create results directory
        run: |
          mkdir -p ${{ github.workspace }}/kics-results
          echo "Created kics-results directory"
          ls -la ${{ github.workspace }}

      - name: KICS scan
        uses: Checkmarx/kics-action@v1.7.0
        with:
          path: terraform
          output_path: kics-results
          output_formats: json,sarif
          fail_on: high
          enable_comments: true
          platform_type: terraform
          output_name: results

      - name: List workspace
        if: always()
        run: |
          echo "Current directory: ${{ github.workspace }}"
          echo "Directory structure:"
          find ${{ github.workspace }} -type f -name "results.*"

      - name: Verify KICS results
        if: always()
        run: |
          echo "Checking KICS results directory:"
          ls -la ${{ github.workspace }}/kics-results/
          if [ -f "${{ github.workspace }}/kics-results/results.sarif" ]; then
            echo "SARIF file exists"
            echo "File size: $(stat -f %z ${{ github.workspace }}/kics-results/results.sarif)"
          else
            echo "SARIF file not found. Searching for it:"
            find ${{ github.workspace }} -type f -name "results.sarif"
          fi
          if [ -f "${{ github.workspace }}/kics-results/results.json" ]; then
            echo "JSON file exists"
            echo "File size: $(stat -f %z ${{ github.workspace }}/kics-results/results.json)"
          else
            echo "JSON file not found. Searching for it:"
            find ${{ github.workspace }} -type f -name "results.json"
          fi

      - name: Upload KICS Results - JSON
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kics-results-json
          path: ${{ github.workspace }}/kics-results/results.json
          retention-days: 7

      - name: Upload KICS Results - SARIF
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: kics-results-sarif
          path: ${{ github.workspace }}/kics-results/results.sarif
          retention-days: 7

      - name: Upload KICS Results to Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: ${{ github.workspace }}/kics-results/results.sarif
          category: KICS
